AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Example based on the AWS doco
Resources:
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
          SourceSecurityGroupName: 'sg-notreal'
  ElasticacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:    
      Engine: memcached
      AZMode: cross-az
      CacheNodeType: cache.t2.micro
      NumCacheNodes: 3
      VpcSecurityGroupIds:
        - !GetAtt 
          - ElasticacheSecurityGroup
          - GroupId